name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - name: Checkout PicoRuby
        uses: actions/checkout@v7
        with:
          repository: picoruby/picoruby
          ref: c9681b351c651016937830c810837877d232317e
          submodules: recursive
          path: picoruby
      - name: Checkout picoruby-mackerel
        uses: actions/checkout@v7
        with:
          path: picoruby/mrbgems/picoruby-mackerel
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.0
          bundler-cache: true
          working-directory: picoruby
      - name: Test
        run: bundle exec rake 'test:gems:picoruby[picoruby-mackerel]'
        working-directory: picoruby

  build-pages:
    if: github.event_name != 'pull_request'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy-pages:
    if: github.event_name != 'pull_request'
    needs: build-pages
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: false
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
